spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mandoo_dev
    username: root
    password: hurmong7942@
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true
    generate-ddl: true

upload:
  path: D:\\image
