spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mandoo_dev
    username: root
    password: hurmong7942@
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true
    generate-ddl: true

upload:
  path: "C:\\Users\\USER\\Desktop\\mandoo_front\\mandoo_Frontend\\src\\images"


logging:
  level:
    root: INFO  # INFO 이상의 레벨을 출력하도록 설정
    mandooparty.mandoo: DEBUG  # 특정 패키지에 대해 DEBUG 로그를 출력하도록 설정
